repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/PyCQA/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: poetry-export
        name: poetry export requirements.txt
        entry: poetry export --without-hashes --format requirements.txt --output requirements.txt --without-hashes
        language: system
        pass_filenames: false
        stages: [ commit ]
        verbose: true
