# Generated by Django 5.0.4 on 2024-04-05 15:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serial_no", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="The batch to which a subject belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.batch",
                    ),
                ),
            ],
        ),
    ]
