# Generated by Django 5.0.4 on 2024-04-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_course_course_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("serial_no", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course to which a batch belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.course",
                    ),
                ),
            ],
        ),
    ]
