# Generated by Django 5.0.4 on 2024-04-05 15:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serial_no", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="The subject to which a topic belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.subject",
                    ),
                ),
            ],
        ),
    ]
