# Generated by Django 5.0.4 on 2024-06-15 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_batch_active_subject_active_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("EVALUATOR", "Evaluator"), ("SCANNER", "Scanner")],
                        default="EVALUATOR",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="course",
            old_name="status",
            new_name="active",
        ),
    ]
