# Generated by Django 5.0.4 on 2024-06-15 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_user_rename_status_course_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=20
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telephone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "profile_picture_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("EVALUATOR", "Evaluator"), ("SCANNER", "Scanner")],
                        default="EVALUATOR",
                        max_length=255,
                    ),
                ),
                (
                    "signature_picture_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
