# Generated by Django 5.0.4 on 2024-06-16 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_employee_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=20
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "telephone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "profile_picture_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grade", models.CharField(max_length=255)),
                ("section", models.CharField(blank=True, max_length=255, null=True)),
                ("parent", models.CharField(blank=True, max_length=255, null=True)),
                ("year_admitted", models.IntegerField(blank=True, null=True)),
                ("house", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "admission_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Single Choice"),
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("BLANKS", "Blanks"),
                            ("TRUE_OR_FALSE", "True Or False"),
                            ("SINGLE_DIGIT", "Single Digit"),
                            ("RANGE", "Range"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ENGLISH", "English"), ("REGIONAL", "Regional")],
                        max_length=255,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        max_length=255,
                    ),
                ),
                ("solution", models.TextField(blank=True, null=True)),
                ("options", models.JSONField()),
                ("answer", models.JSONField(blank=True, null=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="admin_panel.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="admin_panel.topic",
                    ),
                ),
            ],
        ),
    ]
