# Generated by Django 5.0.4 on 2024-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_student_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="BT101", max_length=255),
        ),
    ]
