# Generated by Django 5.0.4 on 2024-07-14 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_alter_topic_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("SEMESTER", "Semester")],
                        default="SEMESTER",
                        max_length=255,
                    ),
                ),
                ("duration", models.IntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        max_length=255,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("semester", models.CharField(blank=True, max_length=255, null=True)),
                ("exam_code", models.CharField(blank=True, max_length=255, null=True)),
                ("total_questions", models.IntegerField(blank=True, null=True)),
                ("total_marks", models.IntegerField(blank=True, null=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
