# Generated by Django 5.0.4 on 2024-07-14 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_alter_exam_duration_alter_exam_total_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="type",
            field=models.CharField(
                choices=[("SEMESTER", "Semester")], default="SEMESTER", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="ExamBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("details", models.TextField()),
                ("mode", models.CharField(max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("batch_conf", models.JSONField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exambatches",
                        to="admin_panel.exam",
                    ),
                ),
            ],
        ),
    ]
