# Generated by Django 5.0.4 on 2024-07-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0011_alter_exam_type_exambatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="type",
            field=models.CharField(
                choices=[("SEMESTER", "Semester")], default="SEMESTER", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="exambatch",
            name="mode",
            field=models.CharField(
                choices=[
                    ("CENTER_BASED_TEST", "Center Based Test"),
                    ("INTERNET_BASED_TEST", "Internet Based Test"),
                    ("INTERNET_BASED_TEST_HYBRID", "Internet Based Test Hybrid"),
                    ("PAPER_BASED_TEST_OSM", "Paper Based Test Osm"),
                    ("PAPER_BASED_TEST_OMR", "Paper Based Test Omr"),
                    ("PAPER_BASED_TEST_ATTACHMENT", "Paper Based Test Attachment"),
                ],
                max_length=255,
            ),
        ),
    ]
