# Generated by Django 5.0.4 on 2024-08-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0019_employee_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="serial_no",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="serial_no",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="serial_no",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.CharField(max_length=255),
        ),
    ]
