# Generated by Django 5.0.4 on 2024-08-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_panel",
            "0020_remove_batch_serial_no_remove_subject_serial_no_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="admin_panel.organization",
            ),
            preserve_default=False,
        ),
    ]
