# Generated by Django 5.0.4 on 2024-08-31 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0021_exam_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="batch",
        ),
        migrations.AddField(
            model_name="subject",
            name="organization",
            field=models.ForeignKey(
                default="f6bff94d-8347-428d-ba64-cca2d8219c66",
                help_text="The organization to which a subject belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="subject",
            field=models.ForeignKey(
                default="940c811f-68ee-4af4-b027-625775a72f33",
                help_text="The subject to which a topic belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.subject",
            ),
            preserve_default=False,
        ),
    ]
