# Generated by Django 5.0.4 on 2024-09-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0022_remove_subject_batch_remove_topic_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="admin_panel.batch",
            ),
            preserve_default=False,
        ),
    ]
