# Generated by Django 5.0.4 on 2024-09-10 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0023_student_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamBatchMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exambatchesexams",
                        to="admin_panel.exam",
                    ),
                ),
                (
                    "exambatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exambatchesbatches",
                        to="admin_panel.exambatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamBatchStudentMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exambatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exambatchbatches",
                        to="admin_panel.exambatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exambatchstudents",
                        to="admin_panel.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamQuestionMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examquestionsexams",
                        to="admin_panel.exam",
                    ),
                ),
                (
                    "exambatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examquestionsexambatch",
                        to="admin_panel.question",
                    ),
                ),
            ],
        ),
    ]
