# Generated by Django 5.0.4 on 2024-09-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0024_exambatchmapping_exambatchstudentmapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exambatchmapping",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exambatchstudentmapping",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examquestionmapping",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.organization",
            ),
            preserve_default=False,
        ),
    ]
