# Generated by Django 5.0.4 on 2024-10-04 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0025_exambatchmapping_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("CENTER_BASED_TEST", "Center Based Test")],
                        default="CENTER_BASED_TEST",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("show_scientific_calculator", models.BooleanField(default=False)),
                ("activity_log", models.BooleanField(default=False)),
                ("is_submit_enable", models.BooleanField(default=False)),
                ("lock_screen", models.BooleanField(default=False)),
                (
                    "maximum_question_attempt",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "test_download_password",
                    models.CharField(blank=True, max_length=100),
                ),
                ("essay_question_time_limit", models.TimeField(blank=True, null=True)),
                ("minimum_question_time", models.TimeField(blank=True, null=True)),
                ("late_login_time", models.IntegerField(blank=True, null=True)),
                ("mandatory_attempt_all_questions", models.BooleanField(default=False)),
                (
                    "essay_question_time_limit_enable",
                    models.BooleanField(default=False),
                ),
                (
                    "enable_backward_forward_movement",
                    models.BooleanField(default=False),
                ),
                ("overall_selection_criteria_1", models.IntegerField(default=95)),
                ("overall_selection_criteria_2", models.IntegerField(default=95)),
                ("section_instructions", models.BooleanField(default=False)),
                ("topic_attempt_limits", models.BooleanField(default=False)),
                ("section_wise_break", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="config",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="admin_panel.examconfiguration",
            ),
            preserve_default=False,
        ),
    ]
