# Generated by Django 5.0.4 on 2024-12-15 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_panel",
            "0030_exambatch_end_time_exambatch_evaluation_end_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamEmployee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EVALUATOR", "Evaluator"),
                            ("MODERATOR", "Moderator"),
                            ("SCANNER", "Scanner"),
                        ],
                        help_text="Role of the employee for this exam",
                        max_length=50,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_assignments",
                        to="admin_panel.employee",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_employees",
                        to="admin_panel.exam",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_employees",
                        to="admin_panel.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("exam", "employee", "role")},
            },
        ),
    ]
